# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty32"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y libfuse-dev fuse flex bison git
    useradd user1
    useradd user2
    useradd user3
    useradd user4
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    git clone https://github.com/scott-linder/rbacfs.git
    cd rbacfs/src
    make
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    cd rbacfs/src
    make install
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    rm -rf rbacfs
    cp -r /vagrant/ .
    cd vagrant
    ./test.sh
  SHELL
end
